server:
  port: ${PORT:8101}

spring:
  application:
    name: validation-service
  kafka:
    producer:
      bootstrap-servers: ${PRODUCER_BOOTSTRAP_SERVER:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    serviceUrl:
      defaultZone: ${discovery.server.url:http://127.0.0.1:8001}/eureka/

kafka:
  validation:
    topic: Booking