server:
  port: ${PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    maxThreadsForPeerReplication: 0
  instance:
    preferIpAddress: true
    hostname: localhost